<a href="https://colab.research.google.com/github/anitahf/Clase---Aprendizaje-Automatico/blob/main/A_H_09_Bosques_Aleatorios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/andres-merino/AprendizajeAutomaticoInicial-05-N0105/blob/main/2-Ejercicios/09-Bosques-Aleatorios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table style="border: none; border-collapse: collapse;">
    <tr>
        <td style="width: 20%; vertical-align: middle; padding-right: 10px;">
            <img src="https://i.imgur.com/nt7hloA.png" width="100">
        </td>
        <td style="width: 2px; text-align: center;">
            <font color="#0030A1" size="7">|</font><br>
            <font color="#0030A1" size="7">|</font>
        </td>
        <td>
            <p style="font-variant: small-caps;"><font color="#0030A1" size="5">
                <b>Facultad de Ciencias Exactas, Naturales y Ambientales</b>
            </font> </p>
            <p style="font-variant: small-caps;"><font color="#0030A1" size="4">
                Aprendizaje Automático Inicial &bull; Bosques Aleatorios
            </font></p>
            <p style="font-style: oblique;"><font color="#0030A1" size="3">
                Ana Hidalgo &bull; 2026-01
            </font></p>
        </td>  
    </tr>
</table>

---
## <font color='264CC7'> Introducción </font>

A lo largo de este taller, aplicaremos un perceptrón para clasificar un conjunto de datos.

Los paquetes necesarios son:

In [ ]:
# Paquetes necesarios
from sklearn.datasets import fetch_openml
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

---
## <font color='264CC7'> Clasificación </font>


### <font color='264CC7'> Preprocesamiento de datos </font>

Primero necesitas el conjunto de datos. Los datos a utilzar son los seleccionados en la clase anterior.

<div style="background-color: #edf1f8; border-color: #264CC7; border-left: 5px solid #264CC7; padding: 0.5em;">
<strong>Ejercicio:</strong><br>
    Carga el conjunto de datos y procésalos:
<ul>
  <li>Muestra algunos datos.</li>
  <li>Muestra una descripción de los datos.</li>
  <li>Escala los datos si es necesario.</li>
</ul>
</div>

In [ ]:
url = "https://raw.githubusercontent.com/anitahf/Clase---Aprendizaje-Automatico/main/dataset.csv"
data = pd.read_csv(url)

In [ ]:
data.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [ ]:
data.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [ ]:
data.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [ ]:
#Selecciono las variables
X = data.drop(columns=[
    "track_genre",
    "track_id",
    "artists",
    "album_name",
    "track_name",
    "Unnamed: 0"
])

y = data["track_genre"]


### <font color='264CC7'> Entrenamiento del modelo y evaluación </font>

<div style="background-color: #edf1f8; border-color: #264CC7; border-left: 5px solid #264CC7; padding: 0.5em;">
<strong>Ejercicio:</strong><br>
    Entrena el modelo y evalúalo:
<ul>
  <li>Entrena el modelo.</li>
  <li>Evalúa el modelo con el conjunto de datos de prueba.</li>
  <li>Genera una matriz de confusión y muestra las métricas de evaluación.</li>
</ul>
</div>

In [ ]:
#Dividir los datos
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
modelo = RandomForestClassifier(
    n_estimators=100,
    max_depth=20,
    random_state=42
)

In [ ]:
modelo.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, random_state=42)

In [ ]:
y_pred = modelo.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy del modelo:", round(accuracy, 2))

Accuracy del modelo: 0.32

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.3232456140350877
                   precision    recall  f1-score   support

         acoustic       0.26      0.26      0.26       200
         afrobeat       0.41      0.36      0.38       200
         alt-rock       0.05      0.04      0.04       200
      alternative       0.07      0.07      0.07       200
          ambient       0.34      0.35      0.35       200
            anime       0.18      0.12      0.15       200
      black-metal       0.57      0.62      0.60       200
        bluegrass       0.42      0.57      0.48       200
            blues       0.17      0.12      0.14       200
           brazil       0.06      0.05      0.05       200
        breakbeat       0.51      0.43      0.47       200
          british       0.11      0.06      0.07       200
         cantopop       0.31      0.28      0.29       200
    chicago-house       0.50      0.48      0.49       200
         children       0.50      0.52      0.51       200
            chill       0.16      0.15      0.16       200
        classical       0.56      0.56      0.56       200
             club       0.42      0.26      0.32       200
           comedy       0.91      0.84      0.88       200
          country       0.59      0.51      0.55       200
            dance       0.33      0.35      0.34       200
        dancehall       0.28      0.33      0.30       200
      death-metal       0.31      0.43      0.36       200
       deep-house       0.15      0.21      0.17       200
   detroit-techno       0.54      0.55      0.54       200
            disco       0.25      0.21      0.23       200
           disney       0.52      0.36      0.43       200
    drum-and-bass       0.62      0.60      0.61       200
              dub       0.12      0.11      0.11       200
          dubstep       0.11      0.15      0.12       200
              edm       0.06      0.07      0.06       200
          electro       0.24      0.19      0.21       200
       electronic       0.09      0.04      0.05       200
              emo       0.19      0.14      0.16       200
             folk       0.13      0.09      0.11       200
            forro       0.39      0.58      0.47       200
           french       0.38      0.29      0.33       200
             funk       0.29      0.28      0.29       200
           garage       0.24      0.14      0.18       200
           german       0.40      0.25      0.31       200
           gospel       0.25      0.36      0.29       200
             goth       0.19      0.10      0.13       200
        grindcore       0.81      0.90      0.85       200
           groove       0.12      0.09      0.10       200
           grunge       0.19      0.21      0.20       200
           guitar       0.45      0.33      0.38       200
            happy       0.51      0.47      0.49       200
        hard-rock       0.09      0.07      0.08       200
         hardcore       0.32      0.35      0.33       200
        hardstyle       0.51      0.56      0.53       200
      heavy-metal       0.32      0.38      0.34       200
          hip-hop       0.31      0.35      0.33       200
       honky-tonk       0.86      0.80      0.83       200
            house       0.11      0.12      0.12       200
              idm       0.59      0.47      0.52       200
           indian       0.19      0.20      0.20       200
            indie       0.05      0.03      0.04       200
        indie-pop       0.10      0.09      0.10       200
       industrial       0.26      0.17      0.20       200
          iranian       0.76      0.78      0.77       200
          j-dance       0.43      0.48      0.45       200
           j-idol       0.50      0.62      0.56       200
            j-pop       0.15      0.14      0.14       200
           j-rock       0.09      0.09      0.09       200
             jazz       0.45      0.45      0.45       200
            k-pop       0.39      0.43      0.41       200
             kids       0.68      0.70      0.69       200
            latin       0.13      0.14      0.14       200
           latino       0.06      0.06      0.06       200
            malay       0.25      0.20      0.22       200
         mandopop       0.24      0.28      0.26       200
            metal       0.05      0.06      0.06       200
        metalcore       0.26      0.33      0.29       200
   minimal-techno       0.33      0.46      0.38       200
              mpb       0.13      0.15      0.14       200
          new-age       0.54      0.61      0.58       200
            opera       0.43      0.48      0.45       200
           pagode       0.39      0.48      0.43       200
            party       0.42      0.57      0.48       200
            piano       0.43      0.40      0.41       200
              pop       0.20      0.22      0.21       200
         pop-film       0.29      0.45      0.35       200
        power-pop       0.34      0.35      0.35       200
progressive-house       0.23      0.23      0.23       200
       psych-rock       0.16      0.15      0.16       200
             punk       0.04      0.04      0.04       200
        punk-rock       0.06      0.07      0.06       200
            r-n-b       0.17      0.12      0.14       200
           reggae       0.05      0.04      0.04       200
        reggaeton       0.02      0.02      0.02       200
             rock       0.22      0.18      0.20       200
      rock-n-roll       0.28      0.47      0.36       200
       rockabilly       0.22      0.16      0.18       200
          romance       0.70      0.83      0.76       200
              sad       0.24      0.32      0.27       200
            salsa       0.54      0.74      0.63       200
            samba       0.36      0.43      0.39       200
        sertanejo       0.43      0.54      0.48       200
       show-tunes       0.38      0.38      0.38       200
singer-songwriter       0.06      0.06      0.06       200
              ska       0.22      0.30      0.26       200
            sleep       0.84      0.81      0.83       200
       songwriter       0.03      0.04      0.03       200
             soul       0.25      0.20      0.22       200
          spanish       0.31      0.12      0.17       200
            study       0.61      0.88      0.72       200
          swedish       0.36      0.17      0.23       200
        synth-pop       0.25      0.17      0.20       200
            tango       0.63      0.76      0.69       200
           techno       0.13      0.12      0.12       200
           trance       0.42      0.41      0.42       200
         trip-hop       0.31      0.29      0.30       200
          turkish       0.29      0.35      0.32       200
      world-music       0.37      0.42      0.40       200

         accuracy                           0.32     22800
        macro avg       0.32      0.32      0.32     22800
     weighted avg       0.32      0.32      0.32     22800

El modelo de Bosques Aleatorios tiene un resultado normal, con un accuracy del 32%. Esto pasa porque hay muchos géneros musicales y varios se parecen bastante entre sí. El modelo reconoce mejor los géneros que tienen un sonido más marcado, pero le cuesta diferenciar los que son similares.